import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import stylesNew from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <div className={`${stylesNew.wholeWebBg} border border-slate-900`}>
            <Navbar />
          </div>

          <div className={`${stylesNew.wholeWebBg} border border-slate-900`}>{children}</div>
          <div className={`${stylesNew.wholeWebBg} border border-slate-900`}>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
